"""Isolated CMNIST A/O/Pi spectral and flatness panel."""

TASK_ID = "TASK-AOPI-SPECTRAL-AND-FLATNESS-PANEL"
PRIMARY_METHODS = ("ERM", "IRMv1", "VREX", "CORAL", "FISHR", "MLDG", "SPECTRAL_NORM_REG", "SPECTRAL_REG_2024", "SVB_ORTHDNN", "STABLE_RANK_NORM", "SAM", "ASAM")
PRIMARY_SEEDS = (10, 11, 12, 13, 14)
VERDICTS = (
    "SPECTRAL-FLATNESS-PANEL-PARTIAL",
    "SPECTRAL-FLATNESS-PANEL-INCOMPLETE",
    "METHOD-FIDELITY-UNRESOLVED",
    "CONTINUATION-PARTIAL",
    "INVALID",
)
