"""Isolated multi-method CMNIST A/O/Pi mechanism survey."""

TASK_ID = "TASK-AOPI-MULTIMETHOD-MECHANISM-SURVEY"
PRIMARY_METHODS = ("ERM", "IRMv1", "VREX", "CORAL")
PRIMARY_SEEDS = (10, 11, 12, 13, 14)
VERDICTS = (
    "MULTIMETHOD-MECHANISM-SURVEY-PASS",
    "MULTIMETHOD-MECHANISM-SURVEY-PARTIAL",
    "MULTIMETHOD-MECHANISM-SURVEY-FAIL",
    "MULTIMETHOD-MECHANISM-SURVEY-INVALID",
)
