"""Isolated expanded CMNIST A/O/Pi algorithm-panel survey."""

TASK_ID = "TASK-AOPI-ALGORITHM-PANEL-EXPANSION-FISHR-MLDG-RANK"
PRIMARY_METHODS = ("ERM", "IRMv1", "VREX", "CORAL", "FISHR", "MLDG", "WEIGHT_NUCLEAR", "FEATURE_NUCLEAR")
PRIMARY_SEEDS = (10, 11, 12, 13, 14)
VERDICTS = (
    "ALGORITHM-PANEL-EXPANSION-PASS",
    "ALGORITHM-PANEL-EXPANSION-PARTIAL",
    "ALGORITHM-PANEL-EXPANSION-FAIL",
    "ALGORITHM-PANEL-EXPANSION-INVALID",
)
