"""Join source-defined semantic responses to A/O_S geometry without invalid codomain sums."""
from pathlib import Path
import json, pandas as pd, numpy as np
ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'round3_redesign/semantic_mechanism_bridge'; BASE=ROOT/'round3_redesign/task3_aopi_multimethod_mechanism_survey/results'; NAMES=['source_env0_color','source_env1_color','evaluation_color','source_label_noise','evaluation_label_noise','source_color_common','source_color_contrast','color_global','color_shift','noise_global','noise_shift']
def run():
 s=pd.read_csv(OUT/'legacy_semantic_response_summary.csv'); s['opaque_direction_id']=s['opaque_direction_id'].astype(str); s['semantic_direction']=s['opaque_direction_id'].map(lambda x:NAMES[int(x[1:])]); a=pd.read_csv(BASE/'geometry_A.csv');o=pd.read_csv(BASE/'geometry_O.csv');
 keep=['method','seed','opaque_direction_id','A_norm','A_normalized_norm','A_rank_primary'];s=s.merge(a[keep],on=['method','seed','opaque_direction_id'],how='left').merge(o[['method','seed','opaque_direction_id','O_norm','O_normalized_norm','O_rank_primary']],on=['method','seed','opaque_direction_id'],how='left');
 s['exposure_to_task_ratio']=s['O_norm']/(s['A_norm']+1e-12);s['response_to_task_ratio']=s['source_bank_response_norm']/(s['A_norm']+1e-12);s['response_to_exposure_ratio']=s['source_bank_response_norm']/(s['O_norm']+1e-12);s.to_csv(OUT/'aopi_conditioned_semantic_response.csv',index=False)
 q=s[s.source_only==True].groupby(['method','semantic_direction','K'])[['A_norm','O_norm','source_bank_response_norm','exposure_to_task_ratio','response_to_task_ratio']].mean().reset_index();q.to_csv(OUT/'aopi_conditioned_semantic_summary.csv',index=False)
 lines=['# A/O-conditioned semantic response audit','', 'This audit restores the A/O main line. Semantic response is joined to the task sensitivity operator A and source observability operator O_S for the same method, seed and opaque direction. A and O_S remain in their declared codomains; no invalid A+O projection is formed.','', 'For source-side semantic directions, the report records raw task sensitivity, source observability, response magnitude, and ratios. These are descriptive coordinates, not a causal decomposition.','']
 for k in [1,5,20]: lines += [f'## K={k}','',q[q.K==k].pivot(index='semantic_direction',columns='method',values='response_to_exposure_ratio').round(4).to_string(),'']
 lines += ['## BIRM/LoRA-BIRM boundary','', 'Official BIRM and LoRA-BIRM checkpoints are not merged into this full-network table. Their existing A/O/Pi artifact is head-only and lacks the full-network continuation state; it remains a separate representation/head analysis.','', '## Verdict','', '`NO-POSITIVE-SEMANTIC-MECHANISM-CANDIDATE`: this audit supplies the missing A/O-conditioned semantic coordinates, but it does not yet test held-out finite behavior or an intervention that changes one semantic component while holding A/O fixed.']
 (OUT/'aopi_conditioned_semantic_report.md').write_text('\n'.join(lines)+'\n')
 prov={'inputs':['legacy_semantic_response_summary.csv','geometry_A.csv','geometry_O.csv'],'codomain_rule':'A and O_S are reported separately; no direct sum or projection','source_only_directions':['source_env0_color','source_env1_color','source_label_noise','source_color_common','source_color_contrast'],'birm_boundary':'head-only separate artifact','verdict':'NO-POSITIVE-SEMANTIC-MECHANISM-CANDIDATE'};(OUT/'aopi_semantic_bridge_provenance.json').write_text(json.dumps(prov,indent=2)+'\n');print('rows',len(s))
if __name__=='__main__':run()
